# Generated by Django 2.1 on 2018-08-26 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_auto_20180824_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(default=None, max_length=50)),
                ('avatar_url', models.URLField()),
                ('html_url', models.URLField(default=None)),
                ('organization', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='organization.Organizations')),
            ],
        ),
    ]
