# Generated by Django 2.1 on 2018-08-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(default=None, max_length=50)),
                ('name', models.CharField(default=None, max_length=50)),
                ('description', models.CharField(default=None, max_length=200)),
                ('avatar_url', models.URLField(default=None)),
                ('blog', models.URLField(default=None)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('public_repos', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
