# Generated by Django 2.1 on 2018-08-24 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organization',
            new_name='Organizations',
        ),
    ]
